# Generated by Django 2.0.7 on 2018-08-13 21:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neekap', '0003_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
