# Generated by Django 2.0.7 on 2018-08-13 21:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neekap', '0004_auto_20180813_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='contents',
            field=ckeditor.fields.RichTextField(default='none'),
        ),
    ]
